### ISSUE TITLE
US Streets Client throws response.payload.map is not a function

### ISSUE THREAD

**Issue by alexj99** [smarty/smartystreets-javascript-sdk#43]
Getting this error from us-street service
`TypeError: n.payload.map is not a function
    at main.c036dd1….js:2
    at main.c036dd1….js:2
    at main.c036dd1….js:2
    at main.c036dd1….js:2
    at MutationObserver.a (main.c036dd1….js:2)
    at t.invoke (polyfills.f1627db….js:2)
    at n.runGuarded (polyfills.f1627db….js:2)
    at MutationObserver.<anonymous> (polyfills.f1627db….js:2)`

My request is: `https://(My host name)/(My host name)?street=6080+CENTER+DRIVE+SUITE+850&city=LOS+ANGELES&state=CA&zipcode=90045&match=invalid&candidates=5&agent=smartystreets+(sdk:javascript@1.11.3)&key=(My embedded key)`

The response is a 200 code. Not really sure where to look except here.

**Comment by alexj99** [comment]
After removing the batch lookups the error is still happening

**Comment by jcrob2** [comment]
Hi @alexj99. Did you find what your issue was?
