### ISSUE TITLE
Missing zip code

### ISSUE THREAD

**Issue by jassent** [smarty/smartystreets-javascript-sdk#62]
The SDK [Suggestion.js](https://github.com/smarty/smartystreets-javascript-sdk/blob/master/src/us_autocomplete/Suggestion.js) is missing the zipcode

This makes it unusable for doing an autocomplete that is mailable...

**Comment by dave-smartystreets** [comment]
Please see the `autocomplete-pro` version: https://github.com/smarty/smartystreets-javascript-sdk/blob/master/src/us_autocomplete_pro/Suggestion.js which does contain the zipcode.  The `Suggestion.js` you commented on is for our older legacy version which we're continuing to maintain for users who want to continue using it.
