### ISSUE TITLE
Suggestion model do not contain source param

### ISSUE THREAD

**Issue by thaliemuk** [smarty/smartystreets-javascript-sdk#64]
class Suggestion {
	constructor(responseData) {
		this.streetLine = responseData.street_line;
		this.secondary = responseData.secondary;
		this.city = responseData.city;
		this.state = responseData.state;
		this.zipcode = responseData.zipcode;
		this.entries = responseData.entries;
	}
} 
Suggestion should also include "source" param in the constructor.
the source is returned from the lookup api but then disappears in the function buildSuggestionsFromResponse, since its not building it in the suggestion constructor

**Comment by smartyskon** [comment]
An implementation of this has been released in version 3.2.1. Details found here: [(https://github.com/smartystreets/changelog/blob/master/sdk/javascript.md#321---2023-10-16)]
