### ISSUE TITLE
Upgrade axios dependency to a secure version

### ISSUE THREAD

**Issue by najeebusears** [smarty/smartystreets-javascript-sdk#76]
As per [this](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx) advisory, axios versions >= 0.8.1 and < 1.6.0 are vulnerable to CSRF. Since `axios` is a direct dependency for smartystreets-javascript-sdk, the axios upgrade to version >=1.6.0  is required

**Comment by camiblanch** [comment]
Related to #74 

We will be looking into applying this fix soon
