### ISSUE TITLE
How to Upgrade from Standard to Core US Street Address API?

### ISSUE THREAD

**Issue by Yofret-Rios** [smarty/smartystreets-javascript-sdk#80]
Hello, I'm not sure where to ask this question, but we recently got an update to upgrade our Smarty Street implementation from **Standard** to **Core**, according to the documentation, we need to add 2 new parameters to activate the **Core**. 

We need to add the `license ` and `match` query parameters to the API calls, from the source code I found how to add the `license` but I'm not sure how to add `match`.

How can we add `match` query parameter using the JS SDK for Smarty Street?

Thanks in advance for any assistance!

**Comment by smartystreets-frontend** [comment]
Please reach out to our [support team](https://www.smarty.com/contact/support).  They're fantastic!
